services:

  clients-api:
    env_file: .env
    image: "${CLIENTS_API_IMAGE_NAME}"
    environment:
      - DB_USERNAME=${CLIENTS_DB_USERNAME}
      - DB_PASSWORD=${CLIENTS_DB_PASSWORD}
      - DB_DATABASE=${CLIENTS_DB_NAME}
      - DB_PORT=${CLIENTS_DB_PORT}
      - DB_HOST=${CLIENTS_DB_HOST}
      - API_JWT_SECRET=${CLIENTS_JWT_SECRET}
      - API_JWT_ALGORITHM=${CLIENTS_JWT_ALGORITHM}
      - API_JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${CLIENTS_JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - SMTP_HOST=${CLIENTS_SMTP_HOST}
      - SMTP_PORT=${CLIENTS_SMTP_PORT}
      - SMTP_LOGIN_EMAIL=${CLIENTS_SMTP_LOGIN_EMAIL}
      - SMTP_LOGIN_PASSWORD=${CLIENTS_SMTP_LOGIN_PASSWORD}
      - REDIS_HOST=${CLIENTS_REDIS_HOST}
      - REDIS_PORT=${CLIENTS_REDIS_PORT}
      - MAXIMUM_CLIENT_MATCHES_PER_DAY=${CLIENTS_MAXIMUM_MATCHES_FOR_DAY}
    ports:
      - "8080:8080"
    volumes:
    - ./app/static:/static

  redis:
    env_file: .env
    image: redis:latest
    volumes:
      - redis_data:/data
    restart: unless-stopped


networks:
  default:
    name: ${CLIENTS_NETWORK}
    external: true

volumes:
  redis_data:
    name: redis_data