services:

  clients-api:
    env_file: .env
    image: "${CLIENTS_API_IMAGE_NAME}"
    environment:
      - DB_USERNAME=${CLIENTS_DB_USERNAME}
      - DB_PASSWORD=${CLIENTS_DB_PASSWORD}
      - DB_DATABASE=${CLIENTS_DB_NAME}
      - DB_PORT=${CLIENTS_DB_PORT}
      - DB_HOST=${CLIENTS_DB_HOST}
      - API_JWT_SECRET=${CLIENTS_JWT_SECRET}
      - API_JWT_ALGORITHM=${CLIENTS_JWT_ALGORITHM}
      - API_JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${CLIENTS_JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
    ports:
      - "8080:8080"
    volumes:
    - ./app/static:/static

networks:
  default:
    name: ${CLIENTS_NETWORK}
    external: true
